package ar.com.ProyectoClub.Dominio;

// Generated 14-sep-2016 13:31:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Alquiler generated by hbm2java
 */
@SuppressWarnings("serial")
public class Alquiler implements java.io.Serializable {

	private Integer nroAlquiler;
	private Socios socios;
	private Nosocio nosocio;
	private Inmuebles inmuebles;
	private Caja caja;
	private Date fechaActual;
	private Date horaActual;
	private Date fechaReserva;
	private Date horaReserva;
	private float precioTotal;

	public Alquiler() {
	}

	public Alquiler(Inmuebles inmuebles, Caja caja, Date fechaActual,
			Date horaActual, Date fechaReserva, Date horaReserva,
			float precioTotal) {
		this.inmuebles = inmuebles;
		this.caja = caja;
		this.fechaActual = fechaActual;
		this.horaActual = horaActual;
		this.fechaReserva = fechaReserva;
		this.horaReserva = horaReserva;
		this.precioTotal = precioTotal;
	}

	public Alquiler(Socios socios, Nosocio nosocio, Inmuebles inmuebles,
			Caja caja, Date fechaActual, Date horaActual, Date fechaReserva,
			Date horaReserva, float precioTotal) {
		this.socios = socios;
		this.nosocio = nosocio;
		this.inmuebles = inmuebles;
		this.caja = caja;
		this.fechaActual = fechaActual;
		this.horaActual = horaActual;
		this.fechaReserva = fechaReserva;
		this.horaReserva = horaReserva;
		this.precioTotal = precioTotal;
	}

	public Integer getNroAlquiler() {
		return this.nroAlquiler;
	}

	public void setNroAlquiler(Integer nroAlquiler) {
		this.nroAlquiler = nroAlquiler;
	}

	public Socios getSocios() {
		return this.socios;
	}

	public void setSocios(Socios socios) {
		this.socios = socios;
	}

	public Nosocio getNosocio() {
		return this.nosocio;
	}

	public void setNosocio(Nosocio nosocio) {
		this.nosocio = nosocio;
	}

	public Inmuebles getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Inmuebles inmuebles) {
		this.inmuebles = inmuebles;
	}

	public Caja getCaja() {
		return this.caja;
	}

	public void setCaja(Caja caja) {
		this.caja = caja;
	}

	public Date getFechaActual() {
		return this.fechaActual;
	}

	public void setFechaActual(Date fechaActual) {
		this.fechaActual = fechaActual;
	}

	public Date getHoraActual() {
		return this.horaActual;
	}

	public void setHoraActual(Date horaActual) {
		this.horaActual = horaActual;
	}

	public Date getFechaReserva() {
		return this.fechaReserva;
	}

	public void setFechaReserva(Date fechaReserva) {
		this.fechaReserva = fechaReserva;
	}

	public Date getHoraReserva() {
		return this.horaReserva;
	}

	public void setHoraReserva(Date horaReserva) {
		this.horaReserva = horaReserva;
	}

	public float getPrecioTotal() {
		return this.precioTotal;
	}

	public void setPrecioTotal(float precioTotal) {
		this.precioTotal = precioTotal;
	}

}
