package ar.com.ProyectoClub.Dominio;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Caja generated by hbm2java
 */
public class Caja implements java.io.Serializable {

	private Integer idCaja;
	private Date fecha;
	private String descripcion;
	private float monto;
	private float subTotal;
	private Set cuotas = new HashSet(0);
	private Set alquilers = new HashSet(0);

	public Caja() {
	}

	public Caja(Date fecha, String descripcion, float monto, float subTotal) {
		this.fecha = fecha;
		this.descripcion = descripcion;
		this.monto = monto;
		this.subTotal = subTotal;
	}

	public Caja(Date fecha, String descripcion, float monto, float subTotal,
			Set cuotas, Set alquilers) {
		this.fecha = fecha;
		this.descripcion = descripcion;
		this.monto = monto;
		this.subTotal = subTotal;
		this.cuotas = cuotas;
		this.alquilers = alquilers;
	}

	public Integer getIdCaja() {
		return this.idCaja;
	}

	public void setIdCaja(Integer idCaja) {
		this.idCaja = idCaja;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public float getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(float subTotal) {
		this.subTotal = subTotal;
	}

	public Set getCuotas() {
		return this.cuotas;
	}

	public void setCuotas(Set cuotas) {
		this.cuotas = cuotas;
	}

	public Set getAlquilers() {
		return this.alquilers;
	}

	public void setAlquilers(Set alquilers) {
		this.alquilers = alquilers;
	}

}
