package ar.com.ProyectoClub.Dominio;
// Generated 19-oct-2016 11:03:04 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private Integer idCategoria;
	private String nombre;
	private String descripcion;
	private float descuento;
	private Set socioses = new HashSet(0);

	public Categoria() {
	}

	public Categoria(String nombre, String descripcion, float descuento) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.descuento = descuento;
	}

	public Categoria(String nombre, String descripcion, float descuento,
			Set socioses) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.descuento = descuento;
		this.socioses = socioses;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getDescuento() {
		return this.descuento;
	}

	public void setDescuento(float descuento) {
		this.descuento = descuento;
	}

	public Set getSocioses() {
		return this.socioses;
	}

	public void setSocioses(Set socioses) {
		this.socioses = socioses;
	}

}
