package ar.com.ProyectoClub.Dominio;
import java.util.Date;

/**
 * Cuota generated by hbm2java
 */
public class Cuota implements java.io.Serializable {

	private Integer id;
	private Caja caja;
	private Socios socios;
	private Date fecha;
	private float monto;
	private String estado;

	public Cuota() {
	}

	public Cuota(Caja caja, Socios socios, Date fecha, float monto,
			String estado) {
		this.caja = caja;
		this.socios = socios;
		this.fecha = fecha;
		this.monto = monto;
		this.estado = estado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Caja getCaja() {
		return this.caja;
	}

	public void setCaja(Caja caja) {
		this.caja = caja;
	}

	public Socios getSocios() {
		return this.socios;
	}

	public void setSocios(Socios socios) {
		this.socios = socios;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
