package ar.com.ProyectoClub.Dominio;
import java.util.HashSet;
import java.util.Set;

/**
 * Nosocio generated by hbm2java
 */
public class Nosocio implements java.io.Serializable {

	private Integer dniNoSocio;
	private Personas personas;
	private Set alquilers = new HashSet(0);

	public Nosocio() {
	}

	public Nosocio(Personas personas) {
		this.personas = personas;
	}

	public Nosocio(Personas personas, Set alquilers) {
		this.personas = personas;
		this.alquilers = alquilers;
	}

	public Integer getDniNoSocio() {
		return this.dniNoSocio;
	}

	public void setDniNoSocio(Integer dniNoSocio) {
		this.dniNoSocio = dniNoSocio;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public Set getAlquilers() {
		return this.alquilers;
	}

	public void setAlquilers(Set alquilers) {
		this.alquilers = alquilers;
	}

}
