package ar.com.ProyectoClub.Dominio;

// Generated 14-sep-2016 13:31:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Nosocio generated by hbm2java
 */
@SuppressWarnings("serial")
public class Nosocio implements java.io.Serializable {

	private int dniNoSocio;
	private Personas personas;
	@SuppressWarnings("rawtypes")
	private Set alquilers = new HashSet(0);

	public Nosocio() {
	}

	public Nosocio(Personas personas) {
		this.personas = personas;
	}

	@SuppressWarnings("rawtypes")
	public Nosocio(Personas personas, Set alquilers) {
		this.personas = personas;
		this.alquilers = alquilers;
	}

	public int getDniNoSocio() {
		return this.dniNoSocio;
	}

	public void setDniNoSocio(int dniNoSocio) {
		this.dniNoSocio = dniNoSocio;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	@SuppressWarnings("rawtypes")
	public Set getAlquilers() {
		return this.alquilers;
	}

	@SuppressWarnings("rawtypes")
	public void setAlquilers(Set alquilers) {
		this.alquilers = alquilers;
	}

}
