package ar.com.ProyectoClub.Dominio;

// Generated 14-sep-2016 13:31:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Personas generated by hbm2java
 */
@SuppressWarnings("serial")
public class Personas implements java.io.Serializable {

	private int dni;
	private String nombre;
	private String apellido;
	private int telefono;
	private String domicilio;
	private Date fechanacimiento;
	private Socios socios;
	private Nosocio nosocio;

	public Personas() {
	}

	public Personas(int dni, String nombre, String apellido, int telefono,
			String domicilio, Date fechanacimiento) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.domicilio = domicilio;
		this.fechanacimiento = fechanacimiento;
	}

	public Personas(int dni, String nombre, String apellido, int telefono,
			String domicilio, Date fechanacimiento, Socios socios,
			Nosocio nosocio) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.domicilio = domicilio;
		this.fechanacimiento = fechanacimiento;
		this.socios = socios;
		this.nosocio = nosocio;
	}

	public int getDni() {
		return this.dni;
	}

	public void setDni(int dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	public Socios getSocios() {
		return this.socios;
	}

	public void setSocios(Socios socios) {
		this.socios = socios;
	}

	public Nosocio getNosocio() {
		return this.nosocio;
	}

	public void setNosocio(Nosocio nosocio) {
		this.nosocio = nosocio;
	}

}
