package ar.com.ProyectoClub.Dominio;
import java.util.Date;

/**
 * Personas generated by hbm2java
 */
public class Personas implements java.io.Serializable {

	private Integer dni;
	private String nombre;
	private String apellido;
	private Integer telefono;
	private String domicilio;
	private Date fechanacimiento;
	private Socios socios;
	private Nosocio nosocio;

	public Personas() {
	}

	public Personas(Integer dni, String nombre, String apellido,
			Integer telefono, String domicilio, Date fechanacimiento) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.domicilio = domicilio;
		this.fechanacimiento = fechanacimiento;
	}

	public Personas(Integer dni, String nombre, String apellido,
			Integer telefono, String domicilio, Date fechanacimiento,
			Socios socios, Nosocio nosocio) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.domicilio = domicilio;
		this.fechanacimiento = fechanacimiento;
		this.socios = socios;
		this.nosocio = nosocio;
	}

	public Integer getDni() {
		return this.dni;
	}

	public void setDni(Integer dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	public Socios getSocios() {
		return this.socios;
	}

	public void setSocios(Socios socios) {
		this.socios = socios;
	}

	public Nosocio getNosocio() {
		return this.nosocio;
	}

	public void setNosocio(Nosocio nosocio) {
		this.nosocio = nosocio;
	}

}
