package ar.com.ProyectoClub.Dominio;

// Generated 14-sep-2016 13:31:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Socios generated by hbm2java
 */
@SuppressWarnings("serial")
public class Socios implements java.io.Serializable {

	private int dniSocios;
	private Categoria categoria;
	private Personas personas;
	private String sexo;
	private String estado;
	private String nacionalidad;
	private String estadocivil;
	private Date fechaingreso;
	private int idx;
	@SuppressWarnings("rawtypes")
	private Set alquilers = new HashSet(0);
	@SuppressWarnings("rawtypes")
	private Set cuotas = new HashSet(0);

	public Socios() {
	}

	public Socios(Categoria categoria, Personas personas, String sexo,
			String estado, String nacionalidad, String estadocivil,
			Date fechaingreso, int idx) {
		this.categoria = categoria;
		this.personas = personas;
		this.sexo = sexo;
		this.estado = estado;
		this.nacionalidad = nacionalidad;
		this.estadocivil = estadocivil;
		this.fechaingreso = fechaingreso;
		this.idx = idx;
	}

	@SuppressWarnings("rawtypes")
	public Socios(Categoria categoria, Personas personas, String sexo,
			String estado, String nacionalidad, String estadocivil,
			Date fechaingreso, int idx, Set alquilers, Set cuotas) {
		this.categoria = categoria;
		this.personas = personas;
		this.sexo = sexo;
		this.estado = estado;
		this.nacionalidad = nacionalidad;
		this.estadocivil = estadocivil;
		this.fechaingreso = fechaingreso;
		this.idx = idx;
		this.alquilers = alquilers;
		this.cuotas = cuotas;
	}

	public int getDniSocios() {
		return this.dniSocios;
	}

	public void setDniSocios(int dniSocios) {
		this.dniSocios = dniSocios;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public String getEstadocivil() {
		return this.estadocivil;
	}

	public void setEstadocivil(String estadocivil) {
		this.estadocivil = estadocivil;
	}

	public Date getFechaingreso() {
		return this.fechaingreso;
	}

	public void setFechaingreso(Date fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

	public int getIdx() {
		return this.idx;
	}

	public void setIdx(int idx) {
		this.idx = idx;
	}

	@SuppressWarnings("rawtypes")
	public Set getAlquilers() {
		return this.alquilers;
	}

	@SuppressWarnings("rawtypes")
	public void setAlquilers(Set alquilers) {
		this.alquilers = alquilers;
	}

	@SuppressWarnings("rawtypes")
	public Set getCuotas() {
		return this.cuotas;
	}

	@SuppressWarnings("rawtypes")
	public void setCuotas(Set cuotas) {
		this.cuotas = cuotas;
	}

}
