/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ProyectoClub.AVista;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import app.bolivia.swing.JCTextField;
import ar.com.ProyectoClub.BControlador.ControllerCoordinador;

import java.awt.Color;
import javax.swing.border.CompoundBorder;
import javax.swing.border.LineBorder;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextField;
import com.toedter.calendar.JDateChooser;
import javax.swing.border.TitledBorder;
import java.awt.Toolkit;

/**
 *
 * @author Rojeru San CL
 */
public class PantallaHistCuota extends JDialog{
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	public static javax.swing.JTable tablaCuotas;
	public JTextField txtNomApe;
	private ControllerCoordinador miCoordinador; //objeto miCoordinador que permite la relacion entre esta clase y la clase ControllerCoordinador
	public JTextField txtTotal;
	private JLabel lblTotalEncontrados;
	// End of variables declaration//GEN-END:variables

    /**
     * Creates new form Usuarios
     */
    public PantallaHistCuota(PantallaCobranzaCuota miVentanaCobranza,boolean activo) {
    	super(miVentanaCobranza,activo);
    	setIconImage(Toolkit.getDefaultToolkit().getImage(PantallaHistCuota.class.getResource("/ar/com/ProyectoClub/AVista/icon/iconoPaloma.png")));
        initComponents();
        tablaCuotas.getTableHeader().setDefaultRenderer(new ar.com.ProyectoClub.AVista.EstiloVentanas.EstiloTablaHeader());
        //tablaCuotas.setDefaultRenderer(Object.class, new ar.com.ProyectoClub.AVista.EstiloVentanas.EstiloTablaRenderer());
        tablaCuotas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCuotas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();

        setTitle("HISTORIAL CUOTA SOCIO");
        jPanel4.setLayout(null);

        jPanel1.setBackground(Color.LIGHT_GRAY);

        tablaCuotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PERIODO", "FECHA PAGO", "DESCRIPCION", "IMPORTE $"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCuotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tablaCuotas);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        JLabel lblNewLabel = new JLabel("APELLIDO Y NOMBRE");
        lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
        lblNewLabel.setForeground(new Color(0, 0, 0));
        lblNewLabel.setBounds(10, 24, 146, 14);
        jPanel4.add(lblNewLabel);
        
        txtNomApe = new JTextField();
        txtNomApe.setEditable(false);
        txtNomApe.setColumns(10);
        txtNomApe.setBackground(new Color(250, 250, 210));
        txtNomApe.setBounds(170, 20, 425, 27);
        jPanel4.add(txtNomApe);
        
        txtTotal = new JTextField();
        txtTotal.setEditable(false);
        txtTotal.setColumns(10);
        txtTotal.setBackground(new Color(250, 250, 210));
        txtTotal.setBounds(608, 87, 49, 20);
        jPanel4.add(txtTotal);
        
        lblTotalEncontrados = new JLabel("TOTAL ENCONTRADOS");
        lblTotalEncontrados.setForeground(Color.BLACK);
        lblTotalEncontrados.setFont(new Font("Tahoma", Font.PLAIN, 14));
        lblTotalEncontrados.setBounds(454, 87, 157, 14);
        jPanel4.add(lblTotalEncontrados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }
    
    public void setCoordinador(ControllerCoordinador miCoordinador) {
		this.miCoordinador=miCoordinador;
	}
}
