package ar.com.ProyectoClub.Modelo.Dominio;
// Generated 26-oct-2016 13:24:02 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Caja generated by hbm2java
 */
public class Caja implements java.io.Serializable {

	private Integer idCaja;
	private Date fecha;
	private String descripcion;
	private float monto;
	private float subTotal;
	private CajaCuota cajaCuota;
	private CajaAlquiler cajaAlquiler;

	public Caja() {
	}

	public Caja(Date fecha, String descripcion, float monto, float subTotal) {
		this.fecha = fecha;
		this.descripcion = descripcion;
		this.monto = monto;
		this.subTotal = subTotal;
	}

	public Caja(Date fecha, String descripcion, float monto, float subTotal,
			CajaCuota cajaCuota, CajaAlquiler cajaAlquiler) {
		this.fecha = fecha;
		this.descripcion = descripcion;
		this.monto = monto;
		this.subTotal = subTotal;
		this.cajaCuota = cajaCuota;
		this.cajaAlquiler = cajaAlquiler;
	}

	public Integer getIdCaja() {
		return this.idCaja;
	}

	public void setIdCaja(Integer idCaja) {
		this.idCaja = idCaja;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public float getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(float subTotal) {
		this.subTotal = subTotal;
	}

	public CajaCuota getCajaCuota() {
		return this.cajaCuota;
	}

	public void setCajaCuota(CajaCuota cajaCuota) {
		this.cajaCuota = cajaCuota;
	}

	public CajaAlquiler getCajaAlquiler() {
		return this.cajaAlquiler;
	}

	public void setCajaAlquiler(CajaAlquiler cajaAlquiler) {
		this.cajaAlquiler = cajaAlquiler;
	}

}
