package ar.com.ProyectoClub.Modelo.Dominio;
// Generated 26-oct-2016 13:24:02 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuota generated by hbm2java
 */
public class Cuota implements java.io.Serializable {

	private Integer id;
	private Socios socios;
	private Date fecha;
	private float monto;
	private String estado;
	private Set cajaCuotas = new HashSet(0);

	public Cuota() {
	}

	public Cuota(Socios socios, Date fecha, float monto, String estado) {
		this.socios = socios;
		this.fecha = fecha;
		this.monto = monto;
		this.estado = estado;
	}

	public Cuota(Socios socios, Date fecha, float monto, String estado,
			Set cajaCuotas) {
		this.socios = socios;
		this.fecha = fecha;
		this.monto = monto;
		this.estado = estado;
		this.cajaCuotas = cajaCuotas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Socios getSocios() {
		return this.socios;
	}

	public void setSocios(Socios socios) {
		this.socios = socios;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getCajaCuotas() {
		return this.cajaCuotas;
	}

	public void setCajaCuotas(Set cajaCuotas) {
		this.cajaCuotas = cajaCuotas;
	}

}
