package ar.com.ProyectoClub.Modelo.Dominio;
// Generated 26-oct-2016 13:24:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Nosocio generated by hbm2java
 */
public class Nosocio implements java.io.Serializable {

	private Integer dniNoSocio;
	private Personas personas;
	private boolean habilitado;
	private Set alquilers = new HashSet(0);

	public Nosocio() {
	}

	public Nosocio(Personas personas, boolean habilitado) {
		this.personas = personas;
		this.habilitado = habilitado;
	}

	public Nosocio(Personas personas, boolean habilitado, Set alquilers) {
		this.personas = personas;
		this.habilitado = habilitado;
		this.alquilers = alquilers;
	}

	public Integer getDniNoSocio() {
		return this.dniNoSocio;
	}

	public void setDniNoSocio(Integer dniNoSocio) {
		this.dniNoSocio = dniNoSocio;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	public Set getAlquilers() {
		return this.alquilers;
	}

	public void setAlquilers(Set alquilers) {
		this.alquilers = alquilers;
	}

}
