package ar.com.ProyectoClub.Modelo.Entidades;

// Generated 10-nov-2016 12:43:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.validator.constraints.NotBlank;

import ar.com.ProyectoClub.Modelo.Persistencia.Dao.Caption;

/**
 * Alquiler generated by hbm2java
 */
public class Alquiler implements java.io.Serializable {
	
	@NotBlank
	@Caption("Numero de alquiler")
	private Integer nroAlquiler;
	private Inmuebles inmuebles;
	@NotBlank
	@Caption("Fecha actual")
	private Date fechaActual;
	@NotBlank
	@Caption("Hora Actual")
	private Date horaActual;
	@NotBlank
	@Caption("Fecha de reserva")
	private Date fechaReserva;
	@NotBlank
	@Caption("Hora reserva")
	private Date horaReserva;
	@NotBlank
	@Caption("Total")
	private float precioTotal;
	private boolean activo;
	private SocioAlquiler socioAlquiler;
	private NosocioAlquiler nosocioAlquiler;
	private Set cajaAlquilers = new HashSet(0);

	public Alquiler() {
	}

	public Alquiler(Inmuebles inmuebles, Date fechaActual, Date horaActual,
			Date fechaReserva, Date horaReserva, float precioTotal,
			boolean activo) {
		this.inmuebles = inmuebles;
		this.fechaActual = fechaActual;
		this.horaActual = horaActual;
		this.fechaReserva = fechaReserva;
		this.horaReserva = horaReserva;
		this.precioTotal = precioTotal;
		this.activo = activo;
	}

	public Alquiler(Inmuebles inmuebles, Date fechaActual, Date horaActual,
			Date fechaReserva, Date horaReserva, float precioTotal,
			boolean activo, SocioAlquiler socioAlquiler,
			NosocioAlquiler nosocioAlquiler, Set cajaAlquilers) {
		this.inmuebles = inmuebles;
		this.fechaActual = fechaActual;
		this.horaActual = horaActual;
		this.fechaReserva = fechaReserva;
		this.horaReserva = horaReserva;
		this.precioTotal = precioTotal;
		this.activo = activo;
		this.socioAlquiler = socioAlquiler;
		this.nosocioAlquiler = nosocioAlquiler;
		this.cajaAlquilers = cajaAlquilers;
	}

	public Integer getNroAlquiler() {
		return this.nroAlquiler;
	}

	public void setNroAlquiler(Integer nroAlquiler) {
		this.nroAlquiler = nroAlquiler;
	}

	public Inmuebles getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Inmuebles inmuebles) {
		this.inmuebles = inmuebles;
	}

	public Date getFechaActual() {
		return this.fechaActual;
	}

	public void setFechaActual(Date fechaActual) {
		this.fechaActual = fechaActual;
	}

	public Date getHoraActual() {
		return this.horaActual;
	}

	public void setHoraActual(Date horaActual) {
		this.horaActual = horaActual;
	}

	public Date getFechaReserva() {
		return this.fechaReserva;
	}

	public void setFechaReserva(Date fechaReserva) {
		this.fechaReserva = fechaReserva;
	}

	public Date getHoraReserva() {
		return this.horaReserva;
	}

	public void setHoraReserva(Date horaReserva) {
		this.horaReserva = horaReserva;
	}

	public float getPrecioTotal() {
		return this.precioTotal;
	}

	public void setPrecioTotal(float precioTotal) {
		this.precioTotal = precioTotal;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public SocioAlquiler getSocioAlquiler() {
		return this.socioAlquiler;
	}

	public void setSocioAlquiler(SocioAlquiler socioAlquiler) {
		this.socioAlquiler = socioAlquiler;
	}

	public NosocioAlquiler getNosocioAlquiler() {
		return this.nosocioAlquiler;
	}

	public void setNosocioAlquiler(NosocioAlquiler nosocioAlquiler) {
		this.nosocioAlquiler = nosocioAlquiler;
	}

	public Set getCajaAlquilers() {
		return this.cajaAlquilers;
	}

	public void setCajaAlquilers(Set cajaAlquilers) {
		this.cajaAlquilers = cajaAlquilers;
	}

}
