package ar.com.ProyectoClub.Modelo.Entidades;

// Generated 10-nov-2016 12:43:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
@SuppressWarnings("serial")
public class Categoria implements java.io.Serializable {

	private Integer idCategoria;
	private String nombre;
	private String descripcion;
	private float descuento;
	private boolean habilitado;
	@SuppressWarnings("rawtypes")
	private Set socioses = new HashSet(0);

	public Categoria() {
	}

	public Categoria(String nombre, String descripcion, float descuento,
			boolean habilitado) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.descuento = descuento;
		this.habilitado = habilitado;
	}

	@SuppressWarnings("rawtypes")
	public Categoria(String nombre, String descripcion, float descuento,
			boolean habilitado, Set socioses) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.descuento = descuento;
		this.habilitado = habilitado;
		this.socioses = socioses;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getDescuento() {
		return this.descuento;
	}

	public void setDescuento(float descuento) {
		this.descuento = descuento;
	}

	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	@SuppressWarnings("rawtypes")
	public Set getSocioses() {
		return this.socioses;
	}

	@SuppressWarnings("rawtypes")
	public void setSocioses(Set socioses) {
		this.socioses = socioses;
	}

}
