package ar.com.ProyectoClub.Modelo.Entidades;

// Generated 10-nov-2016 12:43:34 by Hibernate Tools 3.4.0.CR1

/**
 * NosocioAlquiler generated by hbm2java
 */
public class NosocioAlquiler implements java.io.Serializable {

	private Integer nroAlquiler;
	private Nosocio nosocio;
	private Alquiler alquiler;

	public NosocioAlquiler() {
	}

	public NosocioAlquiler(Nosocio nosocio, Alquiler alquiler) {
		this.nosocio = nosocio;
		this.alquiler = alquiler;
	}

	public Integer getNroAlquiler() {
		return this.nroAlquiler;
	}

	public void setNroAlquiler(Integer nroAlquiler) {
		this.nroAlquiler = nroAlquiler;
	}

	public Nosocio getNosocio() {
		return this.nosocio;
	}

	public void setNosocio(Nosocio nosocio) {
		this.nosocio = nosocio;
	}

	public Alquiler getAlquiler() {
		return this.alquiler;
	}

	public void setAlquiler(Alquiler alquiler) {
		this.alquiler = alquiler;
	}

}
