package ar.com.ProyectoClub.Modelo.Entidades;

// Generated 10-nov-2016 12:43:34 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import org.hibernate.validator.constraints.NotBlank;

import ar.com.ProyectoClub.Modelo.Persistencia.Dao.Caption;

/**
 * Nosocio generated by hbm2java
 */
@SuppressWarnings("serial")
public class Nosocio implements java.io.Serializable {

	@NotBlank
	@Caption("DNI")
	private Integer dniNoSocio;
	private Personas personas;
	private boolean habilitado;
	@SuppressWarnings("rawtypes")
	private Set nosocioAlquilers = new HashSet(0);

	public Nosocio() {
	}

	public Nosocio(Personas personas, boolean habilitado) {
		this.personas = personas;
		this.habilitado = habilitado;
	}

	@SuppressWarnings("rawtypes")
	public Nosocio(Personas personas, boolean habilitado, Set nosocioAlquilers) {
		this.personas = personas;
		this.habilitado = habilitado;
		this.nosocioAlquilers = nosocioAlquilers;
	}

	public Integer getDniNoSocio() {
		return this.dniNoSocio;
	}

	public void setDniNoSocio(Integer dniNoSocio) {
		this.dniNoSocio = dniNoSocio;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	@SuppressWarnings("rawtypes")
	public Set getNosocioAlquilers() {
		return this.nosocioAlquilers;
	}

	@SuppressWarnings("rawtypes")
	public void setNosocioAlquilers(Set nosocioAlquilers) {
		this.nosocioAlquilers = nosocioAlquilers;
	}

}
