package ar.com.ProyectoClub.Modelo.Entidades;

// Generated 10-nov-2016 12:43:34 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.validator.constraints.NotBlank;

import ar.com.ProyectoClub.Modelo.Persistencia.Dao.Caption;

/**
 * Socios generated by hbm2java
 */
public class Socios implements java.io.Serializable {
	
	@NotBlank
	@Caption("DNI del socio")
	private Integer dniSocios;
	private Categoria categoria;
	private Personas personas;
	@NotBlank
	@Caption("Matricula")
	private Integer matricula;
	@NotBlank
	@Caption("Numero de socio")
	private Integer nroSocio;
	private String sexo;
	private String estado;
	private String nacionalidad;
	private String estadocivil;
	@NotBlank
	@Caption("Fecha de ingreso")
	private Date fechaingreso;
	private boolean habilitado;
	private Set cuotas = new HashSet(0);
	private Set socioAlquilers = new HashSet(0);

	public Socios() {
	}

	public Socios(Categoria categoria, Personas personas, Integer matricula,
			Integer nroSocio, String sexo, String estado, String nacionalidad,
			String estadocivil, Date fechaingreso, boolean habilitado,
			Integer idxCategoria) {
		this.categoria = categoria;
		this.personas = personas;
		this.matricula = matricula;
		this.nroSocio = nroSocio;
		this.sexo = sexo;
		this.estado = estado;
		this.nacionalidad = nacionalidad;
		this.estadocivil = estadocivil;
		this.fechaingreso = fechaingreso;
		this.habilitado = habilitado;
	}

	public Socios(Categoria categoria, Personas personas, Integer matricula,
			Integer nroSocio, String sexo, String estado, String nacionalidad,
			String estadocivil, Date fechaingreso, boolean habilitado,
			Integer idxCategoria, Set cuotas, Set socioAlquilers) {
		this.categoria = categoria;
		this.personas = personas;
		this.matricula = matricula;
		this.nroSocio = nroSocio;
		this.sexo = sexo;
		this.estado = estado;
		this.nacionalidad = nacionalidad;
		this.estadocivil = estadocivil;
		this.fechaingreso = fechaingreso;
		this.habilitado = habilitado;
		this.cuotas = cuotas;
		this.socioAlquilers = socioAlquilers;
	}

	public Integer getDniSocios() {
		return this.dniSocios;
	}

	public void setDniSocios(Integer dniSocios) {
		this.dniSocios = dniSocios;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public Integer getMatricula() {
		return this.matricula;
	}

	public void setMatricula(Integer matricula) {
		this.matricula = matricula;
	}

	public Integer getNroSocio() {
		return this.nroSocio;
	}

	public void setNroSocio(Integer nroSocio) {
		this.nroSocio = nroSocio;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public String getEstadocivil() {
		return this.estadocivil;
	}

	public void setEstadocivil(String estadocivil) {
		this.estadocivil = estadocivil;
	}

	public Date getFechaingreso() {
		return this.fechaingreso;
	}

	public void setFechaingreso(Date fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	public Set getCuotas() {
		return this.cuotas;
	}

	public void setCuotas(Set cuotas) {
		this.cuotas = cuotas;
	}

	public Set getSocioAlquilers() {
		return this.socioAlquilers;
	}

	public void setSocioAlquilers(Set socioAlquilers) {
		this.socioAlquilers = socioAlquilers;
	}

}
