package ar.com.ProyectoClub.Modelo.Entidades;

// Generated 10-nov-2016 12:43:34 by Hibernate Tools 3.4.0.CR1

/**
 * SocioAlquiler generated by hbm2java
 */
public class SocioAlquiler implements java.io.Serializable {

	private Integer nroAlquiler;
	private Socios socios;
	private Alquiler alquiler;

	public SocioAlquiler() {
	}

	public SocioAlquiler(Socios socios, Alquiler alquiler) {
		this.socios = socios;
		this.alquiler = alquiler;
	}

	public Integer getNroAlquiler() {
		return this.nroAlquiler;
	}

	public void setNroAlquiler(Integer nroAlquiler) {
		this.nroAlquiler = nroAlquiler;
	}

	public Socios getSocios() {
		return this.socios;
	}

	public void setSocios(Socios socios) {
		this.socios = socios;
	}

	public Alquiler getAlquiler() {
		return this.alquiler;
	}

	public void setAlquiler(Alquiler alquiler) {
		this.alquiler = alquiler;
	}

}
