package ar.com.ProyectoClub.CModelo.CEntidades;
// Generated 17-sep-2017 22:07:28 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Alquiler generated by hbm2java
 */
public class Alquiler implements java.io.Serializable {

	private Integer nroalquiler;
	private Inmuebles inmuebles;
	private Personas personas;
	private Date fechaactual;
	private Date fechareserva;
	private float montofaltante;
	private float preciototal;
	private byte pagoalquiler;
	private String observaciones;
	private byte activo;

	public Alquiler() {
	}

	public Alquiler(Inmuebles inmuebles, Personas personas, Date fechaactual, Date fechareserva, float montofaltante,
			float preciototal, byte pagoalquiler, String observaciones, byte activo) {
		this.inmuebles = inmuebles;
		this.personas = personas;
		this.fechaactual = fechaactual;
		this.fechareserva = fechareserva;
		this.montofaltante = montofaltante;
		this.preciototal = preciototal;
		this.pagoalquiler = pagoalquiler;
		this.observaciones = observaciones;
		this.activo = activo;
	}

	public Integer getNroalquiler() {
		return this.nroalquiler;
	}

	public void setNroalquiler(Integer nroalquiler) {
		this.nroalquiler = nroalquiler;
	}

	public Inmuebles getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Inmuebles inmuebles) {
		this.inmuebles = inmuebles;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public Date getFechaactual() {
		return this.fechaactual;
	}

	public void setFechaactual(Date fechaactual) {
		this.fechaactual = fechaactual;
	}

	public Date getFechareserva() {
		return this.fechareserva;
	}

	public void setFechareserva(Date fechareserva) {
		this.fechareserva = fechareserva;
	}

	public float getMontofaltante() {
		return this.montofaltante;
	}

	public void setMontofaltante(float montofaltante) {
		this.montofaltante = montofaltante;
	}

	public float getPreciototal() {
		return this.preciototal;
	}

	public void setPreciototal(float preciototal) {
		this.preciototal = preciototal;
	}

	public byte getPagoalquiler() {
		return this.pagoalquiler;
	}

	public void setPagoalquiler(byte pagoalquiler) {
		this.pagoalquiler = pagoalquiler;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public byte getActivo() {
		return this.activo;
	}

	public void setActivo(byte activo) {
		this.activo = activo;
	}

}
