package ar.com.ProyectoClub.CModelo.CEntidades;
// Generated 11-jul-2017 9:12:03 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alquiler generated by hbm2java
 */
public class Alquiler implements java.io.Serializable {

	private Integer nroAlquiler;
	private Inmuebles inmuebles;
	private Personas personas;
	private Date fechaActual;
	private Date horaActual;
	private Date fechaReserva;
	private Date horaReserva;
	private Integer cantidadHora;
	private float precioTotal;
	private String observaciones;
	private boolean PagoAlquiler;
	private boolean activo;
	private Set cajas = new HashSet(0);

	public Alquiler() {
	}

	public Alquiler(Inmuebles inmuebles, Personas personas, Date fechaActual, Date horaActual, Date fechaReserva,
			Date horaReserva, Integer cantidadHora, float precioTotal, String observaciones, boolean activo,boolean PagoAlquiler) {
		this.inmuebles = inmuebles;
		this.personas = personas;
		this.fechaActual = fechaActual;
		this.horaActual = horaActual;
		this.fechaReserva = fechaReserva;
		this.horaReserva = horaReserva;
		this.cantidadHora = cantidadHora;
		this.precioTotal = precioTotal;
		this.observaciones = observaciones;
		this.activo = activo;
		this.PagoAlquiler=PagoAlquiler;
	}

	public Alquiler(Inmuebles inmuebles, Personas personas, Date fechaActual, Date horaActual, Date fechaReserva,
			Date horaReserva, Integer cantidadHora, float precioTotal, String observaciones, boolean activo,boolean PagoAlquiler,
			Set cajas) {
		this.inmuebles = inmuebles;
		this.personas = personas;
		this.fechaActual = fechaActual;
		this.horaActual = horaActual;
		this.fechaReserva = fechaReserva;
		this.horaReserva = horaReserva;
		this.cantidadHora = cantidadHora;
		this.precioTotal = precioTotal;
		this.observaciones = observaciones;
		this.activo = activo;
		this.cajas = cajas;
		this.PagoAlquiler=PagoAlquiler;
	}

	public Integer getNroAlquiler() {
		return this.nroAlquiler;
	}

	public void setNroAlquiler(Integer nroAlquiler) {
		this.nroAlquiler = nroAlquiler;
	}

	public Inmuebles getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Inmuebles inmuebles) {
		this.inmuebles = inmuebles;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public Date getFechaActual() {
		return this.fechaActual;
	}

	public void setFechaActual(Date fechaActual) {
		this.fechaActual = fechaActual;
	}

	public Date getHoraActual() {
		return this.horaActual;
	}

	public void setHoraActual(Date horaActual) {
		this.horaActual = horaActual;
	}

	public Date getFechaReserva() {
		return this.fechaReserva;
	}

	public void setFechaReserva(Date fechaReserva) {
		this.fechaReserva = fechaReserva;
	}

	public Date getHoraReserva() {
		return this.horaReserva;
	}

	public void setHoraReserva(Date horaReserva) {
		this.horaReserva = horaReserva;
	}

	public Integer getCantidadHora() {
		return this.cantidadHora;
	}

	public void setCantidadHora(Integer cantidadHora) {
		this.cantidadHora = cantidadHora;
	}

	public float getPrecioTotal() {
		return this.precioTotal;
	}

	public void setPrecioTotal(float precioTotal) {
		this.precioTotal = precioTotal;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set getCajas() {
		return this.cajas;
	}

	public void setCajas(Set cajas) {
		this.cajas = cajas;
	}
	public void setPagoAlquiler(boolean pagoAlquiler) {
		PagoAlquiler = pagoAlquiler;
	}
	public boolean isPagoAlquiler() {
		return PagoAlquiler;
	}

}
