package ar.com.ProyectoClub.CModelo.CEntidades;
// Generated 01-oct-2017 13:17:29 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Caja generated by hbm2java
 */
public class Caja implements java.io.Serializable {

	private Integer idCaja;
	private Conceptos conceptos;
	private Date fecha;
	private float monto;
	private String descripcion;
	private boolean habilitar;

	public Caja() {
	}

	public Caja(Conceptos conceptos, Date fecha, float monto, String descripcion, boolean habilitar) {
		this.conceptos = conceptos;
		this.fecha = fecha;
		this.monto = monto;
		this.descripcion = descripcion;
		this.habilitar = habilitar;
	}

	public Integer getIdCaja() {
		return this.idCaja;
	}

	public void setIdCaja(Integer idCaja) {
		this.idCaja = idCaja;
	}

	public Conceptos getConceptos() {
		return this.conceptos;
	}

	public void setConceptos(Conceptos conceptos) {
		this.conceptos = conceptos;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isHabilitar() {
		return this.habilitar;
	}

	public void setHabilitar(boolean habilitar) {
		this.habilitar = habilitar;
	}

}
