package ar.com.ProyectoClub.CModelo.CEntidades;

// Generated 07-dic-2016 12:36:53 by Hibernate Tools 3.4.0.CR1

/**
 * CajaAlquiler generated by hbm2java
 */
public class CajaAlquiler implements java.io.Serializable {

	private Integer idCaja;
	private Alquiler alquiler;
	private Caja caja;

	public CajaAlquiler() {
	}

	public CajaAlquiler(Alquiler alquiler, Caja caja) {
		this.alquiler = alquiler;
		this.caja = caja;
	}

	public Integer getIdCaja() {
		return this.idCaja;
	}

	public void setIdCaja(Integer idCaja) {
		this.idCaja = idCaja;
	}

	public Alquiler getAlquiler() {
		return this.alquiler;
	}

	public void setAlquiler(Alquiler alquiler) {
		this.alquiler = alquiler;
	}

	public Caja getCaja() {
		return this.caja;
	}

	public void setCaja(Caja caja) {
		this.caja = caja;
	}

}
