package ar.com.ProyectoClub.CModelo.CEntidades;
// Generated 22-feb-2017 12:40:45 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private Integer idCategoria;
	private String nombre;
	private String descripcion;
	private float monto;
	private float descuento;
	private boolean habilitado;
	private Set personases = new HashSet(0);

	public Categoria() {
	}

	public Categoria(String nombre, String descripcion, float monto, float descuento, boolean habilitado) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.monto = monto;
		this.descuento = descuento;
		this.habilitado = habilitado;
	}

	public Categoria(String nombre, String descripcion, float monto, float descuento, boolean habilitado,
			Set personases) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.monto = monto;
		this.descuento = descuento;
		this.habilitado = habilitado;
		this.personases = personases;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public float getDescuento() {
		return this.descuento;
	}

	public void setDescuento(float descuento) {
		this.descuento = descuento;
	}

	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	public Set getPersonases() {
		return this.personases;
	}

	public void setPersonases(Set personases) {
		this.personases = personases;
	}

}
