package ar.com.ProyectoClub.CModelo.CEntidades;
// Generated 27-nov-2017 19:08:00 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private Integer idCategoria;
	private String nombre;
	private String descripcion;
	private float monto;
	private float descuento;
	private boolean habilitado;
	private Set socioses = new HashSet(0);

	public Categoria() {
	}
	public Categoria(Integer id,String nombre) {
		this.nombre=nombre;
		this.idCategoria=id;
	}

	public Categoria(String nombre, String descripcion, float monto, float descuento, boolean habilitado) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.monto = monto;
		this.descuento = descuento;
		this.habilitado = habilitado;
	}

	public Categoria(String nombre, String descripcion, float monto, float descuento, boolean habilitado,
			Set socioses) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.monto = monto;
		this.descuento = descuento;
		this.habilitado = habilitado;
		this.socioses = socioses;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public float getDescuento() {
		return this.descuento;
	}

	public void setDescuento(float descuento) {
		this.descuento = descuento;
	}

	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	public Set getSocioses() {
		return this.socioses;
	}

	public void setSocioses(Set socioses) {
		this.socioses = socioses;
	}

}
