package ar.com.ProyectoClub.CModelo.CEntidades;
// Generated 11-jul-2017 9:12:03 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuota generated by hbm2java
 */
public class Cuota implements java.io.Serializable {

	private Integer id;
	private Personas personas;
	private Integer mes;
	private Integer anio;
	private Date fechaPago;
	private String descripcion;
	private float importe;
	private String estado;
	private Set cajas = new HashSet(0);

	public Cuota() {
	}

	public Cuota(Personas personas, Integer mes, Integer anio, String descripcion, float importe, String estado) {
		this.personas = personas;
		this.mes = mes;
		this.anio = anio;
		this.descripcion = descripcion;
		this.importe = importe;
		this.estado = estado;
	}

	public Cuota(Personas personas, Integer mes, Integer anio, Date fechaPago, String descripcion, float importe,
			String estado, Set cajas) {
		this.personas = personas;
		this.mes = mes;
		this.anio = anio;
		this.fechaPago = fechaPago;
		this.descripcion = descripcion;
		this.importe = importe;
		this.estado = estado;
		this.cajas = cajas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getImporte() {
		return this.importe;
	}

	public void setImporte(float importe) {
		this.importe = importe;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getCajas() {
		return this.cajas;
	}

	public void setCajas(Set cajas) {
		this.cajas = cajas;
	}

}
