package ar.com.ProyectoClub.CModelo.CEntidades;
// Generated 01-feb-2017 12:33:45 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuota generated by hbm2java
 */
public class Cuota implements java.io.Serializable {

	private Integer id;
	private Sociosa sociosa;
	private Integer mes;
	private Integer anio;
	private Date fechaPago;
	private String descripcion;
	private float importe;
	private String estado;
	private Set cajas = new HashSet(0);

	public Cuota() {
	}

	public Cuota(Sociosa sociosa, Integer mes, Integer anio, String descripcion, float importe, String estado) {
		this.sociosa = sociosa;
		this.mes = mes;
		this.anio = anio;
		this.descripcion = descripcion;
		this.importe = importe;
		this.estado = estado;
	}

	public Cuota(Sociosa sociosa, Integer mes, Integer anio, Date fechaPago, String descripcion, float importe,
			String estado, Set cajas) {
		this.sociosa = sociosa;
		this.mes = mes;
		this.anio = anio;
		this.fechaPago = fechaPago;
		this.descripcion = descripcion;
		this.importe = importe;
		this.estado = estado;
		this.cajas = cajas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Sociosa getSociosa() {
		return this.sociosa;
	}

	public void setSociosa(Sociosa sociosa) {
		this.sociosa = sociosa;
	}

	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getImporte() {
		return this.importe;
	}

	public void setImporte(float importe) {
		this.importe = importe;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getCajas() {
		return this.cajas;
	}

	public void setCajas(Set cajas) {
		this.cajas = cajas;
	}

}
