package ar.com.ProyectoClub.CModelo.CEntidades;
// Generated 23-oct-2017 18:29:51 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Cuota generated by hbm2java
 */
public class Cuota implements java.io.Serializable {

	private Integer idCuota;
	private Socios socios;
	private Date fechageneracion;
	private Date fechapago;
	private String descripcion;
	private Integer importe;
	private String estado;

	public Cuota() {
	}

	public Cuota(Socios socios, Date fechageneracion, Date fechapago, String descripcion, Integer importe,
			String estado) {
		this.socios = socios;
		this.fechageneracion = fechageneracion;
		this.fechapago = fechapago;
		this.descripcion = descripcion;
		this.importe = importe;
		this.estado = estado;
	}

	public Integer getIdCuota() {
		return this.idCuota;
	}

	public void setIdCuota(Integer idCuota) {
		this.idCuota = idCuota;
	}

	public Socios getSocios() {
		return this.socios;
	}

	public void setSocios(Socios socios) {
		this.socios = socios;
	}

	public Date getFechageneracion() {
		return this.fechageneracion;
	}

	public void setFechageneracion(Date fechageneracion) {
		this.fechageneracion = fechageneracion;
	}

	public Date getFechapago() {
		return this.fechapago;
	}

	public void setFechapago(Date fechapago) {
		this.fechapago = fechapago;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getImporte() {
		return this.importe;
	}

	public void setImporte(Integer importe) {
		this.importe = importe;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
