package ar.com.ProyectoClub.CModelo.CEntidades;
// Generated 12-nov-2017 13:20:02 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Inmuebles generated by hbm2java
 */
public class Inmuebles implements java.io.Serializable {

	private Integer idInmubles;
	private String nombre;
	private String direccion;
	private float senial;
	private String descripcion;
	private float preciohora;
	private boolean habilitado;
	private Set alquilers = new HashSet(0);

	public Inmuebles() {
	}

	public Inmuebles(String nombre, String direccion, float senial, String descripcion, float preciohora,
			boolean habilitado) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.senial = senial;
		this.descripcion = descripcion;
		this.preciohora = preciohora;
		this.habilitado = habilitado;
	}

	public Inmuebles(String nombre, String direccion, float senial, String descripcion, float preciohora,
			boolean habilitado, Set alquilers) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.senial = senial;
		this.descripcion = descripcion;
		this.preciohora = preciohora;
		this.habilitado = habilitado;
		this.alquilers = alquilers;
	}

	public Integer getIdInmubles() {
		return this.idInmubles;
	}

	public void setIdInmubles(Integer idInmubles) {
		this.idInmubles = idInmubles;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public float getSenial() {
		return this.senial;
	}

	public void setSenial(float senial) {
		this.senial = senial;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getPreciohora() {
		return this.preciohora;
	}

	public void setPreciohora(float preciohora) {
		this.preciohora = preciohora;
	}

	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	public Set getAlquilers() {
		return this.alquilers;
	}

	public void setAlquilers(Set alquilers) {
		this.alquilers = alquilers;
	}

}
