package ar.com.ProyectoClub.CModelo.CEntidades;

// Generated 26-dic-2016 12:08:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nosocio generated by hbm2java
 */
public class Nosocio implements java.io.Serializable {

	private Integer dni;
	private String nombre;
	private String apellido;
	private String telefono;
	private String domicilio;
	private Date fechaNacimiento;
	private boolean habilitado;
	private Set alquilers = new HashSet(0);
	private Set reservas = new HashSet(0);

	public Nosocio() {
	}

	public Nosocio(Integer dni, String nombre, String apellido,
			String telefono, String domicilio, Date fechaNacimiento,
			boolean habilitado) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.domicilio = domicilio;
		this.fechaNacimiento = fechaNacimiento;
		this.habilitado = habilitado;
	}

	public Nosocio(Integer dni, String nombre, String apellido,
			String telefono, String domicilio, Date fechaNacimiento,
			boolean habilitado, Set alquilers, Set reservas) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.domicilio = domicilio;
		this.fechaNacimiento = fechaNacimiento;
		this.habilitado = habilitado;
		this.alquilers = alquilers;
		this.reservas = reservas;
	}

	public Integer getDni() {
		return this.dni;
	}

	public void setDni(Integer dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	public Set getAlquilers() {
		return this.alquilers;
	}

	public void setAlquilers(Set alquilers) {
		this.alquilers = alquilers;
	}

	public Set getReservas() {
		return this.reservas;
	}

	public void setReservas(Set reservas) {
		this.reservas = reservas;
	}

}
