package ar.com.ProyectoClub.CModelo.CEntidades;

// Generated 07-dic-2016 12:36:53 by Hibernate Tools 3.4.0.CR1

/**
 * NosocioAlquiler generated by hbm2java
 */
public class NosocioAlquiler implements java.io.Serializable {

	private Integer nroAlquiler;
	private Alquiler alquiler;
	private Nosocio nosocio;

	public NosocioAlquiler() {
	}

	public NosocioAlquiler(Alquiler alquiler, Nosocio nosocio) {
		this.alquiler = alquiler;
		this.nosocio = nosocio;
	}

	public Integer getNroAlquiler() {
		return this.nroAlquiler;
	}

	public void setNroAlquiler(Integer nroAlquiler) {
		this.nroAlquiler = nroAlquiler;
	}

	public Alquiler getAlquiler() {
		return this.alquiler;
	}

	public void setAlquiler(Alquiler alquiler) {
		this.alquiler = alquiler;
	}

	public Nosocio getNosocio() {
		return this.nosocio;
	}

	public void setNosocio(Nosocio nosocio) {
		this.nosocio = nosocio;
	}

}
