package ar.com.ProyectoClub.CModelo.CEntidades;
// Generated 22-feb-2017 12:40:45 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas implements java.io.Serializable {

	private Integer dni;
	private Categoria categoria;
	private String nombre;
	private String apellido;
	private String telefono;
	private String domicilio;
	private Date fecNacimiento;
	private Integer nroSocio;
	private Integer matricula;
	private String sexo;
	private String estado;
	private String nacionalidad;
	private String estadoCivil;
	private Date fechaIngreso;
	private boolean habilitado;
	private boolean essocio;
	private Set cuotas = new HashSet(0);
	private Set alquilers = new HashSet(0);

	public Personas() {
	}

	public Personas(Integer dni, String nombre, String apellido, String telefono, String domicilio, Date fecNacimiento,
			boolean habilitado, boolean essocio) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.domicilio = domicilio;
		this.fecNacimiento = fecNacimiento;
		this.habilitado = habilitado;
		this.essocio = essocio;
	}

	public Personas(Integer dni, Categoria categoria, String nombre, String apellido, String telefono, String domicilio,
			Date fecNacimiento, Integer nroSocio, Integer matricula, String sexo, String estado, String nacionalidad,
			String estadoCivil, Date fechaIngreso, boolean habilitado, boolean essocio, Set cuotas, Set alquilers) {
		this.dni = dni;
		this.categoria = categoria;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.domicilio = domicilio;
		this.fecNacimiento = fecNacimiento;
		this.nroSocio = nroSocio;
		this.matricula = matricula;
		this.sexo = sexo;
		this.estado = estado;
		this.nacionalidad = nacionalidad;
		this.estadoCivil = estadoCivil;
		this.fechaIngreso = fechaIngreso;
		this.habilitado = habilitado;
		this.essocio = essocio;
		this.cuotas = cuotas;
		this.alquilers = alquilers;
	}

	public Integer getDni() {
		return this.dni;
	}

	public void setDni(Integer dni) {
		this.dni = dni;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public Date getFecNacimiento() {
		return this.fecNacimiento;
	}

	public void setFecNacimiento(Date fecNacimiento) {
		this.fecNacimiento = fecNacimiento;
	}

	public Integer getNroSocio() {
		return this.nroSocio;
	}

	public void setNroSocio(Integer nroSocio) {
		this.nroSocio = nroSocio;
	}

	public Integer getMatricula() {
		return this.matricula;
	}

	public void setMatricula(Integer matricula) {
		this.matricula = matricula;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	public boolean isEssocio() {
		return this.essocio;
	}

	public void setEssocio(boolean essocio) {
		this.essocio = essocio;
	}

	public Set getCuotas() {
		return this.cuotas;
	}

	public void setCuotas(Set cuotas) {
		this.cuotas = cuotas;
	}

	public Set getAlquilers() {
		return this.alquilers;
	}

	public void setAlquilers(Set alquilers) {
		this.alquilers = alquilers;
	}

}
