package ar.com.ProyectoClub.CModelo.CEntidades;

// Generated 26-dic-2016 12:08:49 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva implements java.io.Serializable {

	private Integer idReserva;
	private Sociosa sociosa;
	private Inmuebles inmuebles;
	private Nosocio nosocio;
	private Date fechaActual;
	private boolean puede;
	private Date fechaReserva;
	private Date horaReserva;

	public Reserva() {
	}

	public Reserva(Inmuebles inmuebles, Date fechaActual, boolean puede,
			Date fechaReserva, Date horaReserva) {
		this.inmuebles = inmuebles;
		this.fechaActual = fechaActual;
		this.puede = puede;
		this.fechaReserva = fechaReserva;
		this.horaReserva = horaReserva;
	}

	public Reserva(Sociosa sociosa, Inmuebles inmuebles, Nosocio nosocio,
			Date fechaActual, boolean puede, Date fechaReserva, Date horaReserva) {
		this.sociosa = sociosa;
		this.inmuebles = inmuebles;
		this.nosocio = nosocio;
		this.fechaActual = fechaActual;
		this.puede = puede;
		this.fechaReserva = fechaReserva;
		this.horaReserva = horaReserva;
	}

	public Integer getIdReserva() {
		return this.idReserva;
	}

	public void setIdReserva(Integer idReserva) {
		this.idReserva = idReserva;
	}

	public Sociosa getSociosa() {
		return this.sociosa;
	}

	public void setSociosa(Sociosa sociosa) {
		this.sociosa = sociosa;
	}

	public Inmuebles getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Inmuebles inmuebles) {
		this.inmuebles = inmuebles;
	}

	public Nosocio getNosocio() {
		return this.nosocio;
	}

	public void setNosocio(Nosocio nosocio) {
		this.nosocio = nosocio;
	}

	public Date getFechaActual() {
		return this.fechaActual;
	}

	public void setFechaActual(Date fechaActual) {
		this.fechaActual = fechaActual;
	}

	public boolean isPuede() {
		return this.puede;
	}

	public void setPuede(boolean puede) {
		this.puede = puede;
	}

	public Date getFechaReserva() {
		return this.fechaReserva;
	}

	public void setFechaReserva(Date fechaReserva) {
		this.fechaReserva = fechaReserva;
	}

	public Date getHoraReserva() {
		return this.horaReserva;
	}

	public void setHoraReserva(Date horaReserva) {
		this.horaReserva = horaReserva;
	}

}
