package ar.com.ProyectoClub.CModelo.CEntidades;
// Generated 17-sep-2017 22:07:28 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Socios generated by hbm2java
 */
public class Socios implements java.io.Serializable {

	private Integer dni;
	private Categoria categoria;
	private Personas personas;
	private Integer matricula;
	private String estado;
	private Date fechaingreso;
	private Set cuotas = new HashSet(0);

	public Socios() {
	}

	public Socios(Categoria categoria, Personas personas, Integer matricula, String estado, Date fechaingreso) {
		this.categoria = categoria;
		this.personas = personas;
		this.matricula = matricula;
		this.estado = estado;
		this.fechaingreso = fechaingreso;
	}

	public Socios(Categoria categoria, Personas personas, Integer matricula, String estado, Date fechaingreso,
			Set cuotas) {
		this.categoria = categoria;
		this.personas = personas;
		this.matricula = matricula;
		this.estado = estado;
		this.fechaingreso = fechaingreso;
		this.cuotas = cuotas;
	}

	public Integer getDni() {
		return this.dni;
	}

	public void setDni(Integer dni) {
		this.dni = dni;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	public Integer getMatricula() {
		return this.matricula;
	}

	public void setMatricula(Integer matricula) {
		this.matricula = matricula;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaingreso() {
		return this.fechaingreso;
	}

	public void setFechaingreso(Date fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

	public Set getCuotas() {
		return this.cuotas;
	}

	public void setCuotas(Set cuotas) {
		this.cuotas = cuotas;
	}

}
