package ar.com.ProyectoClub.CModelo.CEntidades;

// Generated 07-dic-2016 12:36:53 by Hibernate Tools 3.4.0.CR1

/**
 * SocioAlquiler generated by hbm2java
 */
public class SocioAlquiler implements java.io.Serializable {

	private Integer nroAlquiler;
	private Alquiler alquiler;
	private Sociosa sociosa;

	public SocioAlquiler() {
	}

	public SocioAlquiler(Alquiler alquiler, Sociosa sociosa) {
		this.alquiler = alquiler;
		this.sociosa = sociosa;
	}

	public Integer getNroAlquiler() {
		return this.nroAlquiler;
	}

	public void setNroAlquiler(Integer nroAlquiler) {
		this.nroAlquiler = nroAlquiler;
	}

	public Alquiler getAlquiler() {
		return this.alquiler;
	}

	public void setAlquiler(Alquiler alquiler) {
		this.alquiler = alquiler;
	}

	public Sociosa getSociosa() {
		return this.sociosa;
	}

	public void setSociosa(Sociosa sociosa) {
		this.sociosa = sociosa;
	}

}
