package ar.com.ProyectoClub.CModelo.CEntidades;

// Generated 07-dic-2016 12:36:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sociosa generated by hbm2java
 */
public class Sociosa implements java.io.Serializable {

	private Integer dni;
	private Categoria categoria;
	private Integer nroSocio;
	private String nombre;
	private String apellido;
	private String telefono;
	private String domicilio;
	private Date fechaNacimiento;
	private Integer matricula;
	private String sexo;
	private String estado;
	private String nacionalidad;
	private String estadoCivil;
	private Date fechaIngreso;
	private boolean habilitado;
	private Set cuotas = new HashSet(0);
	private Set socioAlquilers = new HashSet(0);

	public Sociosa() {
	}

	public Sociosa(Integer dni, Categoria categoria, Integer nroSocio,
			String nombre, String apellido, String telefono, String domicilio,
			Date fechaNacimiento, Integer matricula, String sexo,
			String estado, String nacionalidad, String estadoCivil,
			Date fechaIngreso, boolean habilitado) {
		this.dni = dni;
		this.categoria = categoria;
		this.nroSocio = nroSocio;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.domicilio = domicilio;
		this.fechaNacimiento = fechaNacimiento;
		this.matricula = matricula;
		this.sexo = sexo;
		this.estado = estado;
		this.nacionalidad = nacionalidad;
		this.estadoCivil = estadoCivil;
		this.fechaIngreso = fechaIngreso;
		this.habilitado = habilitado;
	}

	public Sociosa(Integer dni, Categoria categoria, Integer nroSocio,
			String nombre, String apellido, String telefono, String domicilio,
			Date fechaNacimiento, Integer matricula, String sexo,
			String estado, String nacionalidad, String estadoCivil,
			Date fechaIngreso, boolean habilitado, Set cuotas,
			Set socioAlquilers) {
		this.dni = dni;
		this.categoria = categoria;
		this.nroSocio = nroSocio;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.domicilio = domicilio;
		this.fechaNacimiento = fechaNacimiento;
		this.matricula = matricula;
		this.sexo = sexo;
		this.estado = estado;
		this.nacionalidad = nacionalidad;
		this.estadoCivil = estadoCivil;
		this.fechaIngreso = fechaIngreso;
		this.habilitado = habilitado;
		this.cuotas = cuotas;
		this.socioAlquilers = socioAlquilers;
	}

	public Integer getDni() {
		return this.dni;
	}

	public void setDni(Integer dni) {
		this.dni = dni;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Integer getNroSocio() {
		return this.nroSocio;
	}

	public void setNroSocio(Integer nroSocio) {
		this.nroSocio = nroSocio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Integer getMatricula() {
		return this.matricula;
	}

	public void setMatricula(Integer matricula) {
		this.matricula = matricula;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public boolean isHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(boolean habilitado) {
		this.habilitado = habilitado;
	}

	public Set getCuotas() {
		return this.cuotas;
	}

	public void setCuotas(Set cuotas) {
		this.cuotas = cuotas;
	}

	public Set getSocioAlquilers() {
		return this.socioAlquilers;
	}

	public void setSocioAlquilers(Set socioAlquilers) {
		this.socioAlquilers = socioAlquilers;
	}

}
