package ar.com.ProyectoClub.CModelo.CEntidades;
// Generated 13-feb-2017 12:57:53 by Hibernate Tools 3.5.0.Final

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private String nick;
	private String password;
	private String tipousuario;

	public Usuario() {
	}

	public Usuario(String nick, String password, String tipousuario) {
		this.nick = nick;
		this.password = password;
		this.tipousuario = tipousuario;
	}

	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	public String getNick() {
		return this.nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTipousuario() {
		return this.tipousuario;
	}

	public void setTipousuario(String tipousuario) {
		this.tipousuario = tipousuario;
	}

}
